// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: services/rootfsquota/v1/rootfsquota.proto

package rootfsquota

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RootfsQuotaInfo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Storage              string   `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	HardQuota            int64    `protobuf:"varint,4,opt,name=hard_quota,json=hardQuota,proto3" json:"hard_quota,omitempty"`
	SoftQuota            int64    `protobuf:"varint,5,opt,name=soft_quota,json=softQuota,proto3" json:"soft_quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RootfsQuotaInfo) Reset()      { *m = RootfsQuotaInfo{} }
func (*RootfsQuotaInfo) ProtoMessage() {}
func (*RootfsQuotaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{0}
}
func (m *RootfsQuotaInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RootfsQuotaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RootfsQuotaInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RootfsQuotaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RootfsQuotaInfo.Merge(m, src)
}
func (m *RootfsQuotaInfo) XXX_Size() int {
	return m.Size()
}
func (m *RootfsQuotaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RootfsQuotaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RootfsQuotaInfo proto.InternalMessageInfo

type CreateRootfsQuotaRequest struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Storage              string            `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	SoftQuota            int64             `protobuf:"varint,3,opt,name=soft_quota,json=softQuota,proto3" json:"soft_quota,omitempty"`
	HardQuota            int64             `protobuf:"varint,4,opt,name=hard_quota,json=hardQuota,proto3" json:"hard_quota,omitempty"`
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRootfsQuotaRequest) Reset()      { *m = CreateRootfsQuotaRequest{} }
func (*CreateRootfsQuotaRequest) ProtoMessage() {}
func (*CreateRootfsQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{1}
}
func (m *CreateRootfsQuotaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateRootfsQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateRootfsQuotaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateRootfsQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRootfsQuotaRequest.Merge(m, src)
}
func (m *CreateRootfsQuotaRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateRootfsQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRootfsQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRootfsQuotaRequest proto.InternalMessageInfo

type CreateRootfsQuotaResponse struct {
	RootfsquotaInfo      *RootfsQuotaInfo `protobuf:"bytes,1,opt,name=rootfsquota_info,json=rootfsquotaInfo,proto3" json:"rootfsquota_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateRootfsQuotaResponse) Reset()      { *m = CreateRootfsQuotaResponse{} }
func (*CreateRootfsQuotaResponse) ProtoMessage() {}
func (*CreateRootfsQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{2}
}
func (m *CreateRootfsQuotaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateRootfsQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateRootfsQuotaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateRootfsQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRootfsQuotaResponse.Merge(m, src)
}
func (m *CreateRootfsQuotaResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateRootfsQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRootfsQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRootfsQuotaResponse proto.InternalMessageInfo

type ListRootfsQuotaRequest struct {
	Filters              map[string]string `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PageSize             int32             `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page                 int32             `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListRootfsQuotaRequest) Reset()      { *m = ListRootfsQuotaRequest{} }
func (*ListRootfsQuotaRequest) ProtoMessage() {}
func (*ListRootfsQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{3}
}
func (m *ListRootfsQuotaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListRootfsQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListRootfsQuotaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListRootfsQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRootfsQuotaRequest.Merge(m, src)
}
func (m *ListRootfsQuotaRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListRootfsQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRootfsQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRootfsQuotaRequest proto.InternalMessageInfo

type ListRootfsQuotaResponse struct {
	RootfsquotaList      []*RootfsQuotaInfo `protobuf:"bytes,1,rep,name=rootfsquota_list,json=rootfsquotaList,proto3" json:"rootfsquota_list,omitempty"`
	TotalCount           int32              `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRootfsQuotaResponse) Reset()      { *m = ListRootfsQuotaResponse{} }
func (*ListRootfsQuotaResponse) ProtoMessage() {}
func (*ListRootfsQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{4}
}
func (m *ListRootfsQuotaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListRootfsQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListRootfsQuotaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListRootfsQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRootfsQuotaResponse.Merge(m, src)
}
func (m *ListRootfsQuotaResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListRootfsQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRootfsQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRootfsQuotaResponse proto.InternalMessageInfo

type GetRootfsQuotaRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRootfsQuotaRequest) Reset()      { *m = GetRootfsQuotaRequest{} }
func (*GetRootfsQuotaRequest) ProtoMessage() {}
func (*GetRootfsQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{5}
}
func (m *GetRootfsQuotaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRootfsQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRootfsQuotaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRootfsQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRootfsQuotaRequest.Merge(m, src)
}
func (m *GetRootfsQuotaRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetRootfsQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRootfsQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRootfsQuotaRequest proto.InternalMessageInfo

type UpdateRootfsQuotaRequest struct {
	ID                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RootfsquotaInfo      *RootfsQuotaInfo `protobuf:"bytes,2,opt,name=rootfsquota_info,json=rootfsquotaInfo,proto3" json:"rootfsquota_info,omitempty"`
	UpdateMask           *types.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateRootfsQuotaRequest) Reset()      { *m = UpdateRootfsQuotaRequest{} }
func (*UpdateRootfsQuotaRequest) ProtoMessage() {}
func (*UpdateRootfsQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{6}
}
func (m *UpdateRootfsQuotaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateRootfsQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateRootfsQuotaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateRootfsQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRootfsQuotaRequest.Merge(m, src)
}
func (m *UpdateRootfsQuotaRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateRootfsQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRootfsQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRootfsQuotaRequest proto.InternalMessageInfo

type UpdateRootfsQuotaResponse struct {
	RootfsquotaInfo      *RootfsQuotaInfo `protobuf:"bytes,1,opt,name=rootfsquota_info,json=rootfsquotaInfo,proto3" json:"rootfsquota_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateRootfsQuotaResponse) Reset()      { *m = UpdateRootfsQuotaResponse{} }
func (*UpdateRootfsQuotaResponse) ProtoMessage() {}
func (*UpdateRootfsQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{7}
}
func (m *UpdateRootfsQuotaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateRootfsQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateRootfsQuotaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateRootfsQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRootfsQuotaResponse.Merge(m, src)
}
func (m *UpdateRootfsQuotaResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateRootfsQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRootfsQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRootfsQuotaResponse proto.InternalMessageInfo

type DeleteRootfsQuotaRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRootfsQuotaRequest) Reset()      { *m = DeleteRootfsQuotaRequest{} }
func (*DeleteRootfsQuotaRequest) ProtoMessage() {}
func (*DeleteRootfsQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c03dd6bc36d8dab, []int{8}
}
func (m *DeleteRootfsQuotaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteRootfsQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteRootfsQuotaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteRootfsQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRootfsQuotaRequest.Merge(m, src)
}
func (m *DeleteRootfsQuotaRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteRootfsQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRootfsQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRootfsQuotaRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RootfsQuotaInfo)(nil), "containerd.services.rootfsquota.v1.RootfsQuotaInfo")
	proto.RegisterType((*CreateRootfsQuotaRequest)(nil), "containerd.services.rootfsquota.v1.CreateRootfsQuotaRequest")
	proto.RegisterMapType((map[string]string)(nil), "containerd.services.rootfsquota.v1.CreateRootfsQuotaRequest.LabelsEntry")
	proto.RegisterType((*CreateRootfsQuotaResponse)(nil), "containerd.services.rootfsquota.v1.CreateRootfsQuotaResponse")
	proto.RegisterType((*ListRootfsQuotaRequest)(nil), "containerd.services.rootfsquota.v1.ListRootfsQuotaRequest")
	proto.RegisterMapType((map[string]string)(nil), "containerd.services.rootfsquota.v1.ListRootfsQuotaRequest.FiltersEntry")
	proto.RegisterType((*ListRootfsQuotaResponse)(nil), "containerd.services.rootfsquota.v1.ListRootfsQuotaResponse")
	proto.RegisterType((*GetRootfsQuotaRequest)(nil), "containerd.services.rootfsquota.v1.GetRootfsQuotaRequest")
	proto.RegisterType((*UpdateRootfsQuotaRequest)(nil), "containerd.services.rootfsquota.v1.UpdateRootfsQuotaRequest")
	proto.RegisterType((*UpdateRootfsQuotaResponse)(nil), "containerd.services.rootfsquota.v1.UpdateRootfsQuotaResponse")
	proto.RegisterType((*DeleteRootfsQuotaRequest)(nil), "containerd.services.rootfsquota.v1.DeleteRootfsQuotaRequest")
}

func init() {
	proto.RegisterFile("services/rootfsquota/v1/rootfsquota.proto", fileDescriptor_6c03dd6bc36d8dab)
}

var fileDescriptor_6c03dd6bc36d8dab = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4f, 0x4f, 0xdb, 0x4a,
	0x10, 0x67, 0x1d, 0x02, 0x8f, 0xc9, 0xd3, 0x03, 0x56, 0x3c, 0x9e, 0x9f, 0x51, 0x43, 0x94, 0x13,
	0xbd, 0xd8, 0x22, 0x5c, 0x0a, 0xb4, 0x17, 0xfe, 0x23, 0xd1, 0x43, 0x5d, 0x55, 0xaa, 0x7a, 0x68,
	0xea, 0x24, 0x1b, 0xb3, 0xc2, 0x78, 0x8d, 0x77, 0x1d, 0x09, 0x7a, 0xe1, 0xdc, 0x53, 0xa5, 0xde,
	0x7a, 0xeb, 0x17, 0xe8, 0xe7, 0xe0, 0xd6, 0x1e, 0x7b, 0xaa, 0x4a, 0x4e, 0xfd, 0x18, 0xd5, 0xae,
	0x6d, 0xd5, 0x4d, 0x6c, 0x11, 0x42, 0xd5, 0xdb, 0xee, 0xcc, 0xee, 0xcc, 0x6f, 0x7e, 0x3b, 0xbf,
	0xd1, 0xc2, 0x7d, 0x4e, 0xc2, 0x1e, 0x6d, 0x13, 0x6e, 0x85, 0x8c, 0x89, 0x2e, 0x3f, 0x8b, 0x98,
	0x70, 0xac, 0xde, 0x6a, 0x76, 0x6b, 0x06, 0x21, 0x13, 0x0c, 0xd7, 0xdb, 0xcc, 0x17, 0x0e, 0xf5,
	0x49, 0xd8, 0x31, 0xd3, 0x5b, 0x66, 0xf6, 0x58, 0x6f, 0xd5, 0x58, 0x70, 0x99, 0xcb, 0xd4, 0x71,
	0x4b, 0xae, 0xe2, 0x9b, 0xc6, 0x92, 0xcb, 0x98, 0xeb, 0x11, 0x4b, 0xed, 0x5a, 0x51, 0xd7, 0x22,
	0xa7, 0x81, 0x38, 0x4f, 0x9c, 0xb5, 0x41, 0x67, 0x97, 0x12, 0xaf, 0xd3, 0x3c, 0x75, 0xf8, 0x49,
	0x7c, 0xa2, 0xfe, 0x0e, 0xc1, 0xac, 0xad, 0xf2, 0x3c, 0x91, 0x79, 0x0e, 0xfd, 0x2e, 0xc3, 0x8b,
	0xa0, 0xd1, 0x8e, 0x8e, 0x6a, 0x68, 0x65, 0x66, 0x6b, 0xaa, 0xff, 0x75, 0x59, 0x3b, 0xdc, 0xb1,
	0x35, 0xda, 0xc1, 0x73, 0x50, 0x3a, 0x21, 0xe7, 0xba, 0x26, 0x1d, 0xb6, 0x5c, 0x62, 0x1d, 0xa6,
	0xb9, 0x60, 0xa1, 0xe3, 0x12, 0xbd, 0xa4, 0xac, 0xe9, 0x16, 0xdf, 0x03, 0x38, 0x76, 0xc2, 0x4e,
	0x53, 0xa1, 0xd7, 0x27, 0x6b, 0x68, 0xa5, 0x64, 0xcf, 0x48, 0x8b, 0x4a, 0x23, 0xdd, 0x9c, 0x75,
	0x45, 0xe2, 0x2e, 0xc7, 0x6e, 0x69, 0x51, 0xee, 0xfa, 0x07, 0x0d, 0xf4, 0xed, 0x90, 0x38, 0x82,
	0x64, 0xb0, 0xd9, 0xe4, 0x2c, 0x22, 0x5c, 0xa4, 0x30, 0x50, 0x2e, 0x0c, 0x6d, 0x08, 0x46, 0x26,
	0x4f, 0x69, 0x20, 0xcf, 0x4d, 0x28, 0x5f, 0xc1, 0x94, 0xe7, 0xb4, 0x88, 0xc7, 0xf5, 0x72, 0xad,
	0xb4, 0x52, 0x69, 0x1c, 0x98, 0x37, 0x3f, 0x93, 0x59, 0x84, 0xdb, 0x3c, 0x52, 0xa1, 0x76, 0x7d,
	0x11, 0x9e, 0xdb, 0x49, 0x5c, 0x63, 0x1d, 0x2a, 0x19, 0x73, 0x4e, 0x69, 0x0b, 0x50, 0xee, 0x39,
	0x5e, 0x94, 0x16, 0x16, 0x6f, 0x36, 0xb4, 0x07, 0xa8, 0xfe, 0x1a, 0xfe, 0xcf, 0x49, 0xc5, 0x03,
	0xe6, 0x73, 0x82, 0x5f, 0xc2, 0x5c, 0x06, 0x56, 0x93, 0xfa, 0x5d, 0xa6, 0xa2, 0x56, 0x1a, 0x6b,
	0xa3, 0xd4, 0x30, 0xd0, 0x11, 0xf6, 0x6c, 0xc6, 0x2f, 0x0d, 0xf5, 0xef, 0x08, 0x16, 0x8f, 0x28,
	0x17, 0x39, 0xcf, 0xe3, 0xc0, 0x74, 0x97, 0x7a, 0x82, 0x84, 0x5c, 0x47, 0x8a, 0xb5, 0xfd, 0x51,
	0x32, 0xe6, 0x07, 0x33, 0xf7, 0xe2, 0x48, 0x31, 0x69, 0x69, 0x5c, 0xbc, 0x04, 0x33, 0x81, 0xe3,
	0x92, 0x26, 0xa7, 0x17, 0x31, 0x31, 0x65, 0xfb, 0x2f, 0x69, 0x78, 0x4a, 0x2f, 0x08, 0xc6, 0x30,
	0x19, 0xa4, 0x0d, 0x59, 0xb6, 0xd5, 0xda, 0xd8, 0x80, 0xbf, 0xb3, 0x91, 0x6e, 0xc5, 0xf3, 0x7b,
	0x04, 0xff, 0x0d, 0xa1, 0xcb, 0xa7, 0xd9, 0xa3, 0x5c, 0x24, 0x45, 0xdf, 0x99, 0x66, 0x99, 0x12,
	0x2f, 0x43, 0x45, 0x30, 0xe1, 0x78, 0xcd, 0x36, 0x8b, 0x7c, 0x91, 0x94, 0x0a, 0xca, 0xb4, 0x2d,
	0x2d, 0x75, 0x0b, 0xfe, 0xdd, 0x27, 0x79, 0xaf, 0x50, 0xa0, 0xe1, 0xfa, 0x27, 0x04, 0xfa, 0xb3,
	0xa0, 0x93, 0xaf, 0xac, 0x22, 0xe1, 0xe7, 0x75, 0x93, 0xf6, 0xfb, 0xba, 0x09, 0x6f, 0x42, 0x25,
	0x52, 0x98, 0xd4, 0x64, 0x52, 0x2f, 0x57, 0x69, 0x18, 0x66, 0x3c, 0xbc, 0xcc, 0x74, 0x78, 0x99,
	0x7b, 0x72, 0x78, 0x3d, 0x76, 0xf8, 0x89, 0x0d, 0xf1, 0x71, 0xb9, 0x96, 0x3a, 0xc8, 0x29, 0xe8,
	0x0f, 0xe9, 0xa0, 0x01, 0xfa, 0x0e, 0xf1, 0xc8, 0x6d, 0xd8, 0x6c, 0x7c, 0x2c, 0x43, 0x25, 0x73,
	0x1c, 0xbf, 0x45, 0x30, 0x3f, 0xa4, 0x64, 0xfc, 0xf0, 0x2e, 0xb3, 0xc6, 0x78, 0x34, 0xe6, 0xed,
	0x84, 0xb6, 0x37, 0x08, 0x66, 0x07, 0x7a, 0x1e, 0x6f, 0x8c, 0x2f, 0x63, 0x63, 0x73, 0xac, 0xbb,
	0x09, 0x18, 0xc9, 0xcf, 0xd0, 0x0b, 0x8f, 0xc6, 0x4f, 0x51, 0xa7, 0x8f, 0xc6, 0x4f, 0x71, 0x5b,
	0x5d, 0x22, 0xf8, 0xe7, 0x57, 0xdd, 0xe1, 0xf5, 0x51, 0x22, 0xe6, 0x6a, 0xd5, 0x18, 0xa7, 0x15,
	0x31, 0x85, 0xf9, 0xa1, 0xce, 0x1b, 0x8d, 0x94, 0xa2, 0x86, 0x35, 0x16, 0x87, 0x14, 0xb7, 0x2b,
	0xff, 0x12, 0x5b, 0xad, 0xab, 0xeb, 0xea, 0xc4, 0x97, 0xeb, 0xea, 0xc4, 0x65, 0xbf, 0x8a, 0xae,
	0xfa, 0x55, 0xf4, 0xb9, 0x5f, 0x45, 0xdf, 0xfa, 0x55, 0xf4, 0xe2, 0xc0, 0xa5, 0xe2, 0x38, 0x6a,
	0x99, 0x6d, 0x76, 0x6a, 0xfd, 0xcc, 0x9c, 0x5d, 0x3a, 0x01, 0xb5, 0x0a, 0xbe, 0x41, 0x9b, 0x99,
	0xed, 0xf3, 0x89, 0xd6, 0x94, 0xca, 0xba, 0xf6, 0x23, 0x00, 0x00, 0xff, 0xff, 0xea, 0xd2, 0x34,
	0xb7, 0x36, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RootfsQuotaClient is the client API for RootfsQuota service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RootfsQuotaClient interface {
	CreateRootfsQuota(ctx context.Context, in *CreateRootfsQuotaRequest, opts ...grpc.CallOption) (*CreateRootfsQuotaResponse, error)
	ListRootfsQuota(ctx context.Context, in *ListRootfsQuotaRequest, opts ...grpc.CallOption) (*ListRootfsQuotaResponse, error)
	UpdateRootfsQuota(ctx context.Context, in *UpdateRootfsQuotaRequest, opts ...grpc.CallOption) (*UpdateRootfsQuotaResponse, error)
	GetRootfsQuota(ctx context.Context, in *GetRootfsQuotaRequest, opts ...grpc.CallOption) (*RootfsQuotaInfo, error)
	DeleteRootfsQuota(ctx context.Context, in *DeleteRootfsQuotaRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type rootfsQuotaClient struct {
	cc *grpc.ClientConn
}

func NewRootfsQuotaClient(cc *grpc.ClientConn) RootfsQuotaClient {
	return &rootfsQuotaClient{cc}
}

func (c *rootfsQuotaClient) CreateRootfsQuota(ctx context.Context, in *CreateRootfsQuotaRequest, opts ...grpc.CallOption) (*CreateRootfsQuotaResponse, error) {
	out := new(CreateRootfsQuotaResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.rootfsquota.v1.RootfsQuota/CreateRootfsQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootfsQuotaClient) ListRootfsQuota(ctx context.Context, in *ListRootfsQuotaRequest, opts ...grpc.CallOption) (*ListRootfsQuotaResponse, error) {
	out := new(ListRootfsQuotaResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.rootfsquota.v1.RootfsQuota/ListRootfsQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootfsQuotaClient) UpdateRootfsQuota(ctx context.Context, in *UpdateRootfsQuotaRequest, opts ...grpc.CallOption) (*UpdateRootfsQuotaResponse, error) {
	out := new(UpdateRootfsQuotaResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.rootfsquota.v1.RootfsQuota/UpdateRootfsQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootfsQuotaClient) GetRootfsQuota(ctx context.Context, in *GetRootfsQuotaRequest, opts ...grpc.CallOption) (*RootfsQuotaInfo, error) {
	out := new(RootfsQuotaInfo)
	err := c.cc.Invoke(ctx, "/containerd.services.rootfsquota.v1.RootfsQuota/GetRootfsQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootfsQuotaClient) DeleteRootfsQuota(ctx context.Context, in *DeleteRootfsQuotaRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/containerd.services.rootfsquota.v1.RootfsQuota/DeleteRootfsQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootfsQuotaServer is the server API for RootfsQuota service.
type RootfsQuotaServer interface {
	CreateRootfsQuota(context.Context, *CreateRootfsQuotaRequest) (*CreateRootfsQuotaResponse, error)
	ListRootfsQuota(context.Context, *ListRootfsQuotaRequest) (*ListRootfsQuotaResponse, error)
	UpdateRootfsQuota(context.Context, *UpdateRootfsQuotaRequest) (*UpdateRootfsQuotaResponse, error)
	GetRootfsQuota(context.Context, *GetRootfsQuotaRequest) (*RootfsQuotaInfo, error)
	DeleteRootfsQuota(context.Context, *DeleteRootfsQuotaRequest) (*types.Empty, error)
}

// UnimplementedRootfsQuotaServer can be embedded to have forward compatible implementations.
type UnimplementedRootfsQuotaServer struct {
}

func (*UnimplementedRootfsQuotaServer) CreateRootfsQuota(ctx context.Context, req *CreateRootfsQuotaRequest) (*CreateRootfsQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRootfsQuota not implemented")
}
func (*UnimplementedRootfsQuotaServer) ListRootfsQuota(ctx context.Context, req *ListRootfsQuotaRequest) (*ListRootfsQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRootfsQuota not implemented")
}
func (*UnimplementedRootfsQuotaServer) UpdateRootfsQuota(ctx context.Context, req *UpdateRootfsQuotaRequest) (*UpdateRootfsQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRootfsQuota not implemented")
}
func (*UnimplementedRootfsQuotaServer) GetRootfsQuota(ctx context.Context, req *GetRootfsQuotaRequest) (*RootfsQuotaInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRootfsQuota not implemented")
}
func (*UnimplementedRootfsQuotaServer) DeleteRootfsQuota(ctx context.Context, req *DeleteRootfsQuotaRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRootfsQuota not implemented")
}

func RegisterRootfsQuotaServer(s *grpc.Server, srv RootfsQuotaServer) {
	s.RegisterService(&_RootfsQuota_serviceDesc, srv)
}

func _RootfsQuota_CreateRootfsQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRootfsQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootfsQuotaServer).CreateRootfsQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.rootfsquota.v1.RootfsQuota/CreateRootfsQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootfsQuotaServer).CreateRootfsQuota(ctx, req.(*CreateRootfsQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootfsQuota_ListRootfsQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRootfsQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootfsQuotaServer).ListRootfsQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.rootfsquota.v1.RootfsQuota/ListRootfsQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootfsQuotaServer).ListRootfsQuota(ctx, req.(*ListRootfsQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootfsQuota_UpdateRootfsQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRootfsQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootfsQuotaServer).UpdateRootfsQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.rootfsquota.v1.RootfsQuota/UpdateRootfsQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootfsQuotaServer).UpdateRootfsQuota(ctx, req.(*UpdateRootfsQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootfsQuota_GetRootfsQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootfsQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootfsQuotaServer).GetRootfsQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.rootfsquota.v1.RootfsQuota/GetRootfsQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootfsQuotaServer).GetRootfsQuota(ctx, req.(*GetRootfsQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootfsQuota_DeleteRootfsQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRootfsQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootfsQuotaServer).DeleteRootfsQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.rootfsquota.v1.RootfsQuota/DeleteRootfsQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootfsQuotaServer).DeleteRootfsQuota(ctx, req.(*DeleteRootfsQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RootfsQuota_serviceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.rootfsquota.v1.RootfsQuota",
	HandlerType: (*RootfsQuotaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRootfsQuota",
			Handler:    _RootfsQuota_CreateRootfsQuota_Handler,
		},
		{
			MethodName: "ListRootfsQuota",
			Handler:    _RootfsQuota_ListRootfsQuota_Handler,
		},
		{
			MethodName: "UpdateRootfsQuota",
			Handler:    _RootfsQuota_UpdateRootfsQuota_Handler,
		},
		{
			MethodName: "GetRootfsQuota",
			Handler:    _RootfsQuota_GetRootfsQuota_Handler,
		},
		{
			MethodName: "DeleteRootfsQuota",
			Handler:    _RootfsQuota_DeleteRootfsQuota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rootfsquota/v1/rootfsquota.proto",
}

func (m *RootfsQuotaInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RootfsQuotaInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RootfsQuotaInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.SoftQuota != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.SoftQuota))
		i--
		dAtA[i] = 0x28
	}
	if m.HardQuota != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.HardQuota))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Storage) > 0 {
		i -= len(m.Storage)
		copy(dAtA[i:], m.Storage)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.Storage)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateRootfsQuotaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateRootfsQuotaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateRootfsQuotaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Labels) > 0 {
		for k := range m.Labels {
			v := m.Labels[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintRootfsquota(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintRootfsquota(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintRootfsquota(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.HardQuota != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.HardQuota))
		i--
		dAtA[i] = 0x20
	}
	if m.SoftQuota != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.SoftQuota))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Storage) > 0 {
		i -= len(m.Storage)
		copy(dAtA[i:], m.Storage)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.Storage)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateRootfsQuotaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateRootfsQuotaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateRootfsQuotaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RootfsquotaInfo != nil {
		{
			size, err := m.RootfsquotaInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRootfsquota(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListRootfsQuotaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListRootfsQuotaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListRootfsQuotaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Page != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x18
	}
	if m.PageSize != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Filters) > 0 {
		for k := range m.Filters {
			v := m.Filters[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintRootfsquota(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintRootfsquota(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintRootfsquota(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListRootfsQuotaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListRootfsQuotaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListRootfsQuotaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TotalCount != 0 {
		i = encodeVarintRootfsquota(dAtA, i, uint64(m.TotalCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RootfsquotaList) > 0 {
		for iNdEx := len(m.RootfsquotaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RootfsquotaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRootfsquota(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetRootfsQuotaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRootfsQuotaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRootfsQuotaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateRootfsQuotaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateRootfsQuotaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateRootfsQuotaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UpdateMask != nil {
		{
			size, err := m.UpdateMask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRootfsquota(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RootfsquotaInfo != nil {
		{
			size, err := m.RootfsquotaInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRootfsquota(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateRootfsQuotaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateRootfsQuotaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateRootfsQuotaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RootfsquotaInfo != nil {
		{
			size, err := m.RootfsquotaInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRootfsquota(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteRootfsQuotaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteRootfsQuotaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteRootfsQuotaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintRootfsquota(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRootfsquota(dAtA []byte, offset int, v uint64) int {
	offset -= sovRootfsquota(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RootfsQuotaInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	l = len(m.Storage)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.HardQuota != 0 {
		n += 1 + sovRootfsquota(uint64(m.HardQuota))
	}
	if m.SoftQuota != 0 {
		n += 1 + sovRootfsquota(uint64(m.SoftQuota))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateRootfsQuotaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	l = len(m.Storage)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.SoftQuota != 0 {
		n += 1 + sovRootfsquota(uint64(m.SoftQuota))
	}
	if m.HardQuota != 0 {
		n += 1 + sovRootfsquota(uint64(m.HardQuota))
	}
	if len(m.Labels) > 0 {
		for k, v := range m.Labels {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovRootfsquota(uint64(len(k))) + 1 + len(v) + sovRootfsquota(uint64(len(v)))
			n += mapEntrySize + 1 + sovRootfsquota(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateRootfsQuotaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RootfsquotaInfo != nil {
		l = m.RootfsquotaInfo.Size()
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListRootfsQuotaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Filters) > 0 {
		for k, v := range m.Filters {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovRootfsquota(uint64(len(k))) + 1 + len(v) + sovRootfsquota(uint64(len(v)))
			n += mapEntrySize + 1 + sovRootfsquota(uint64(mapEntrySize))
		}
	}
	if m.PageSize != 0 {
		n += 1 + sovRootfsquota(uint64(m.PageSize))
	}
	if m.Page != 0 {
		n += 1 + sovRootfsquota(uint64(m.Page))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListRootfsQuotaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RootfsquotaList) > 0 {
		for _, e := range m.RootfsquotaList {
			l = e.Size()
			n += 1 + l + sovRootfsquota(uint64(l))
		}
	}
	if m.TotalCount != 0 {
		n += 1 + sovRootfsquota(uint64(m.TotalCount))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetRootfsQuotaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateRootfsQuotaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.RootfsquotaInfo != nil {
		l = m.RootfsquotaInfo.Size()
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.UpdateMask != nil {
		l = m.UpdateMask.Size()
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateRootfsQuotaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RootfsquotaInfo != nil {
		l = m.RootfsquotaInfo.Size()
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeleteRootfsQuotaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovRootfsquota(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovRootfsquota(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRootfsquota(x uint64) (n int) {
	return sovRootfsquota(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *RootfsQuotaInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RootfsQuotaInfo{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Storage:` + fmt.Sprintf("%v", this.Storage) + `,`,
		`HardQuota:` + fmt.Sprintf("%v", this.HardQuota) + `,`,
		`SoftQuota:` + fmt.Sprintf("%v", this.SoftQuota) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateRootfsQuotaRequest) String() string {
	if this == nil {
		return "nil"
	}
	keysForLabels := make([]string, 0, len(this.Labels))
	for k, _ := range this.Labels {
		keysForLabels = append(keysForLabels, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForLabels)
	mapStringForLabels := "map[string]string{"
	for _, k := range keysForLabels {
		mapStringForLabels += fmt.Sprintf("%v: %v,", k, this.Labels[k])
	}
	mapStringForLabels += "}"
	s := strings.Join([]string{`&CreateRootfsQuotaRequest{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Storage:` + fmt.Sprintf("%v", this.Storage) + `,`,
		`SoftQuota:` + fmt.Sprintf("%v", this.SoftQuota) + `,`,
		`HardQuota:` + fmt.Sprintf("%v", this.HardQuota) + `,`,
		`Labels:` + mapStringForLabels + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateRootfsQuotaResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateRootfsQuotaResponse{`,
		`RootfsquotaInfo:` + strings.Replace(this.RootfsquotaInfo.String(), "RootfsQuotaInfo", "RootfsQuotaInfo", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListRootfsQuotaRequest) String() string {
	if this == nil {
		return "nil"
	}
	keysForFilters := make([]string, 0, len(this.Filters))
	for k, _ := range this.Filters {
		keysForFilters = append(keysForFilters, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForFilters)
	mapStringForFilters := "map[string]string{"
	for _, k := range keysForFilters {
		mapStringForFilters += fmt.Sprintf("%v: %v,", k, this.Filters[k])
	}
	mapStringForFilters += "}"
	s := strings.Join([]string{`&ListRootfsQuotaRequest{`,
		`Filters:` + mapStringForFilters + `,`,
		`PageSize:` + fmt.Sprintf("%v", this.PageSize) + `,`,
		`Page:` + fmt.Sprintf("%v", this.Page) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListRootfsQuotaResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRootfsquotaList := "[]*RootfsQuotaInfo{"
	for _, f := range this.RootfsquotaList {
		repeatedStringForRootfsquotaList += strings.Replace(f.String(), "RootfsQuotaInfo", "RootfsQuotaInfo", 1) + ","
	}
	repeatedStringForRootfsquotaList += "}"
	s := strings.Join([]string{`&ListRootfsQuotaResponse{`,
		`RootfsquotaList:` + repeatedStringForRootfsquotaList + `,`,
		`TotalCount:` + fmt.Sprintf("%v", this.TotalCount) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetRootfsQuotaRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetRootfsQuotaRequest{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateRootfsQuotaRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateRootfsQuotaRequest{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`RootfsquotaInfo:` + strings.Replace(this.RootfsquotaInfo.String(), "RootfsQuotaInfo", "RootfsQuotaInfo", 1) + `,`,
		`UpdateMask:` + strings.Replace(fmt.Sprintf("%v", this.UpdateMask), "FieldMask", "types.FieldMask", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateRootfsQuotaResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateRootfsQuotaResponse{`,
		`RootfsquotaInfo:` + strings.Replace(this.RootfsquotaInfo.String(), "RootfsQuotaInfo", "RootfsQuotaInfo", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteRootfsQuotaRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteRootfsQuotaRequest{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringRootfsquota(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *RootfsQuotaInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RootfsQuotaInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RootfsQuotaInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Storage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Storage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardQuota", wireType)
			}
			m.HardQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HardQuota |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftQuota", wireType)
			}
			m.SoftQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SoftQuota |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateRootfsQuotaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateRootfsQuotaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateRootfsQuotaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Storage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Storage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftQuota", wireType)
			}
			m.SoftQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SoftQuota |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardQuota", wireType)
			}
			m.HardQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HardQuota |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Labels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Labels == nil {
				m.Labels = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRootfsquota
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRootfsquota
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRootfsquota
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRootfsquota
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthRootfsquota
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRootfsquota(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Labels[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateRootfsQuotaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateRootfsQuotaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateRootfsQuotaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootfsquotaInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootfsquotaInfo == nil {
				m.RootfsquotaInfo = &RootfsQuotaInfo{}
			}
			if err := m.RootfsquotaInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListRootfsQuotaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListRootfsQuotaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListRootfsQuotaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filters == nil {
				m.Filters = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRootfsquota
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRootfsquota
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRootfsquota
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRootfsquota
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthRootfsquota
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRootfsquota(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRootfsquota
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Filters[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListRootfsQuotaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListRootfsQuotaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListRootfsQuotaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootfsquotaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootfsquotaList = append(m.RootfsquotaList, &RootfsQuotaInfo{})
			if err := m.RootfsquotaList[len(m.RootfsquotaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCount", wireType)
			}
			m.TotalCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRootfsQuotaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRootfsQuotaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRootfsQuotaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateRootfsQuotaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateRootfsQuotaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateRootfsQuotaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootfsquotaInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootfsquotaInfo == nil {
				m.RootfsquotaInfo = &RootfsQuotaInfo{}
			}
			if err := m.RootfsquotaInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateMask == nil {
				m.UpdateMask = &types.FieldMask{}
			}
			if err := m.UpdateMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateRootfsQuotaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateRootfsQuotaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateRootfsQuotaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootfsquotaInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootfsquotaInfo == nil {
				m.RootfsquotaInfo = &RootfsQuotaInfo{}
			}
			if err := m.RootfsquotaInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteRootfsQuotaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteRootfsQuotaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteRootfsQuotaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRootfsquota
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRootfsquota(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRootfsquota
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRootfsquota(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRootfsquota
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRootfsquota
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRootfsquota
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRootfsquota
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRootfsquota
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRootfsquota        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRootfsquota          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRootfsquota = fmt.Errorf("proto: unexpected end of group")
)
