/*
	Copyright The containerd Authors.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

syntax = "proto3";

package containerd.services.disks.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/any.proto";
import weak "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/containerd/containerd/api/services/disks/v1;disks";


service Disks {
	rpc Prepare(PrepareDiskRequest) returns (PrepareDiskResponse);
	rpc View(ViewDiskRequest) returns (ViewDiskResponse);
	rpc Remove(RemoveDiskRequest) returns (google.protobuf.Empty);
	rpc Update(UpdateDiskRequest) returns (UpdateDiskResponse);
	rpc List(ListDiskRequest) returns (ListDiskResponse);
  rpc Save(SaveDiskRequest) returns (google.protobuf.Empty);
}

message SaveDiskRequest {
  string key = 1;
  string version = 2;
}

message PrepareDiskRequest {
  string key  = 1; 
  string size = 2; 
  string storage_type =3;
}

message ViewDiskRequest {
  string key = 1;
}

message RemoveDiskRequest {
  string key = 1;
}

message UpdateDiskRequest {
  string key = 1;
  string size = 2;
  string storage_type =3;
}

message ListDiskRequest {
  string filter     = 1;
  int32 page_size   = 2;
}

message Disk {
  string disk_type = 1;
  string version   = 2;
  string status    = 3;
  string storage_type =4;
}

message PrepareDiskResponse {
  string mount_point = 1;
  int64 size_bytes   = 2;
  Disk disk          = 3;
}

message ViewDiskResponse {
  Disk disk   = 1; 
}

message UpdateDiskResponse {
  Disk disk        = 1;
  string updated_at = 2; 
}

message ListDiskResponse { 
  repeated ListDiskItem items = 1;  
}

message ListDiskItem {
  string key = 1;
  Disk disk  = 2;
}